WebSportOnline/WebSportOnline/Models/KhuyenMai.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSportOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuyenMai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhuyenMai()
        {
            this.SanPhamKhuyenMais = new HashSet<SanPhamKhuyenMai>();
        }
    
        public string MaKM { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public string NoiDung { get; set; }
        public string TenCT { get; set; }
        public string AnhCT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPhamKhuyenMai> SanPhamKhuyenMais { get; set; }
    }
}

WebSportOnline/WebSportOnline/Controllers/KhuyenMaiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using WebSportOnline.Models;
using System.Net;
using System.IO;

namespace WebSportOnline.Controllers
{
    [AuthLog(Roles = "Quản trị viên,Nhân viên")]
    public class KhuyenMaiController : Controller
    {
        //
        // GET: /KhuyenMai/
        public ActionResult Index()
        {
            return View();
        }

        public bool UploadAnh(HttpPostedFileBase file, string tenfile)
        {
            // Verify that the user selected a file
            if (file != null && file.ContentLength > 0)
            {
                var name = Path.GetExtension(file.FileName);
                // extract only the filename
                if (!Path.GetExtension(file.FileName).Equals(".jpg"))
                {
                    return false;
                }
                // store the file inside ~/App_Data/uploads folder
                var path = Path.Combine(Server.MapPath("~/Content/images/khuyenmai/"), tenfile + ".jpg");
                file.SaveAs(path);
                return true;
            }
            // redirect back to the index action to show the form once again
            return false;
        }

        public bool DeleteAnh(string filename)
        {
            string fullPath = Request.MapPath("~/Content/images/khuyenmai/" + filename);
            if (System.IO.File.Exists(fullPath))
            {
                System.IO.File.Delete(fullPath);
                return true;
            }
            return false;
        }

        public ActionResult EditKhuyenMai(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhuyenMaiModel lm = new KhuyenMaiModel();
            KhuyenMai sp = lm.FindById(id);
            if (sp == null)
            {
                return HttpNotFound();
            }
            return View(sp);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditKhuyenMai([Bind(Include = "MaKM,TenCT,NgayBatDau,NgayKetThuc,NoiDung")] KhuyenMai loai, HttpPostedFileBase ad)
        {
            KhuyenMaiModel spm = new KhuyenMaiModel();
            if (ModelState.IsValid)
            {
                spm.EditKhuyenMai(loai);
                UploadAnh(ad, loai.MaKM + "1");
                return RedirectToAction("Index");
            }
            return View(loai);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ThemKhuyenMai([Bind(Include = "TenCT,NgayBatDau,NgayKetThuc,NoiDung")] KhuyenMai loai, HttpPostedFileBase ad)
        {
            KhuyenMaiModel spm = new KhuyenMaiModel();
            if (ModelState.IsValid && spm.KiemTraTen(loai.TenCT))
            {
                string makm = spm.ThemKhuyenMai(loai);
                UploadAnh(ad, makm + "1");
                return RedirectToAction("SuaCTKhuyenMai", new { MaKM = makm });
            }
            return View("Index", loai);
        }

        public ActionResult DeleteKhuyenMai(string id)
        {
            KhuyenMaiModel spm = new KhuyenMaiModel();
            DeleteAnh(spm.FindById(id).AnhCT);
            spm.DeleteKhuyenMai(id);    
            return TimKhuyenMai(null, null, null, null);
        }

        [HttpPost]
        public ActionResult MultibleDel(List<string> lstdel)
        {
            if (lstdel == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            foreach (var item in lstdel)
            {
                KhuyenMaiModel spm = new KhuyenMaiModel();
                DeleteAnh(spm.FindById(item).AnhCT);
                spm.DeleteKhuyenMai(item);
            }
            return TimKhuyenMai(null, null, null, null);
        }

        public ActionResult DeleteSPKhuyenMai(string makm, string masp)
        {
            KhuyenMaiModel spm = new KhuyenMaiModel();
            spm.DeleteSPKhuyenMai(makm, masp);
            
            return RedirectToAction("DSSanPham", new { makm = makm });
        }

        public ActionResult TimKhuyenMai(string key, DateTime? start, DateTime? end, int? page)
        {
            KhuyenMaiModel spm = new KhuyenMaiModel();
            ViewBag.key = key;
            ViewBag.start = start;
            ViewBag.end = end;
            return PhanTrangKhuyenMai(spm.TimKhuyenMai(key, start, end), page, null);
        }

        public ActionResult PhanTrangKhuyenMai(IQueryable<KhuyenMai> lst, int? page, int? pagesize)
        {
            int pageSize = (pagesize ?? 10);
            int pageNumber = (page ?? 1);
            return PartialView("KhuyenMaiPartial", lst.OrderBy(m => m.NgayBatDau).ToPagedList(pageNumber, pageSize));
        }

        public ActionResult kiemtra(string key)
        {
            KhuyenMaiModel spm = new KhuyenMaiModel();
            if (spm.KiemTraTen(key))
                return Json(true, JsonRequestBehavior.AllowGet);
            return Json(false, JsonRequestBehavior.AllowGet);
        }

        public ActionResult CTKhuyenMai(string id)
        {
            KhuyenMaiModel km = new KhuyenMaiModel();
            var lst = km.CTKhuyenMai(id);
            if (lst.Any())
                return PartialView("KhuyenMaiDetail", lst);
            return null;
        }

        [HttpPost]
        public ActionResult ThemSPKhuyenMai(List<SanPhamKhuyenMai> lstkt)
        {
            if (lstkt.Count == 0)
            {
                return RedirectToAction("Index");
            }
            KhuyenMaiModel spm = new KhuyenMaiModel();
            foreach (var item in lstkt)
            {
                if (!string.IsNullOrEmpty(item.MaSP) && !string.IsNullOrEmpty(item.MaKM))
                    spm.ThemSPKhuyenMai(item);
            }
            return RedirectToAction("Index");
        }

        [HttpPost] 
        public ActionResult ThemSP1KhuyenMai([Bind(Include = "MaKM,MaSP,MoTa,GiamGia")] SanPhamKhuyenMai spkm)
        {
            KhuyenMaiModel spm = new KhuyenMaiModel();
            spm.ThemSPKhuyenMai(spkm);
            return RedirectToAction("DSSanPham", new { makm = spkm.MaKM });
        }

        [HttpPost]
        public ActionResult SuaCTKhuyenMai(List<SanPhamKhuyenMai> lstkt)
        {
            if (lstkt.Count == 0)
            {
                return RedirectToAction("Index");
            }
            KhuyenMaiModel spm = new KhuyenMaiModel();
            spm.DelAllSPKM(lstkt[0].MaKM);
            foreach (var item in lstkt)
            {
                if (!string.IsNullOrEmpty(item.MaSP) && !string.IsNullOrEmpty(item.MaKM))
                    spm.ThemSPKhuyenMai(item);
            }
            return RedirectToAction("Index");
        }

        public ActionResult SuaCTKhuyenMai(string MaKM)
        {
            SanPhamModel sp = new SanPhamModel();
            ViewBag.LoaiSP = new SelectList(sp.GetAllLoaiSP(), "MaLoai", "TenLoai");
            ViewBag.makm = MaKM;
            return View("SuaSPKhuyenMai");
        }


        public ActionResult DSSanPham(string key, string maloai, string makm, int? page)
        {
            ViewBag.key = key;
            ViewBag.maloai = maloai;
            ViewBag.makm = makm;
            KhuyenMaiModel km = new KhuyenMaiModel();
            IQueryable<SanPham> lst = km.DSSP(key, maloai, makm);
            if (lst.Any())
                return PhanTrangSP(lst, "DSSanPham", page, null);
            return null;
        }

        public ActionResult DSSanPhamKhuyenMai(string key, string maloai, string makm, int? page)
        {
            ViewBag.key = key;
            ViewBag.maloai = maloai;
            ViewBag.makm = makm;
            KhuyenMaiModel km = new KhuyenMaiModel();
            IQueryable<SanPham> lst = km.DSSanPhamKhuyenMai(key, maloai, makm);
            if (lst.Any())
                return PhanTrangSP(lst, "DSSanPhamKhuyenMai", page, null);
            return null;
        }


        public ActionResult PhanTrangSP(IQueryable<SanPham> lst, string stringview, int? page, int? pagesize)
        {
            int pageSize = (pagesize ?? 10);
            int pageNumber = (page ?? 1);
            return PartialView(stringview, lst.OrderBy(m => m.MaSP).ToPagedList(pageNumber, pageSize));
        }

        [AllowAnonymous]
        public ActionResult KhuyenMaiPost(string id)
        {
            KhuyenMaiModel km = new KhuyenMaiModel();
            return View("KhuyenMaiPostView", km.FindById(id));
        }

    }
}

WebSportOnline/WebSportOnline/Views/KhuyenMai/DSSanPham.cshtml
@using WebSportOnline.Models;
@using PagedList;
@using PagedList.Mvc;
@model PagedList.IPagedList<SanPham>
<script src="~/ckeditor/ckeditor.js"></script>
<script>
    function ThemSPKhuyenMai(val1, val2) {
        $('#show-dialog-detail').fadeIn(500);
        $('#info-ok').click(function () {
            $('#show-dialog-detail').fadeOut(500);
            var giamgia = $('#giamgiainfo').val();
            var mota = CKEDITOR.instances['motainfo'].getData();
            $.ajax({
                url: "/KhuyenMai/ThemSP1KhuyenMai",
                type: 'POST',
                data: { MaKM: val1, MaSP: val2, GiamGia: giamgia, MoTa: mota },
                success: function (result) {
                    $('.Ajax-Table').html(result);
                    timkiemDSSanPhamKhuyenMai(val1);
                },
            });
        });

    }
</script>
<table class="table table-striped table-bordered bootstrap-datatable datatable responsive">
    <thead>
        <tr>
            <th>
                <input type="checkbox" onclick="toggle(this)" />
            </th>
            <th>@Html.DisplayNameFor(model => model.First().TenSP)</th>
            <th>@Html.DisplayNameFor(model => model.First().LoaiSP1.TenLoai)</th>
            <th>@Html.DisplayNameFor(model => model.First().SoLuong)</th>
            <th>@Html.DisplayNameFor(model => model.First().GiaTien)</th>
            <th>Hành động</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <input type="checkbox" name="lstdel" value="@item.MaSP" />
                </td>
                <td class="center">@item.TenSP</td>
                <td class="center">@item.LoaiSP1.TenLoai</td>
                <td class="center">@item.SoLuong</td>
                <td class="center">@string.Format("{0:0,0}", item.GiaTien) VNĐ</td>
                <td class="center">
                    <a class="btn btn-info" href='javascript:ThemSPKhuyenMai("@ViewBag.makm","@item.MaSP")'>
                        <i class="glyphicon glyphicon-plus icon-white"></i>
                        Thêm vào chương trình khuyến mại
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="pagination-holder">
    <div class="row">
        <div class="col-xs-12 col-sm-6 text-left">
            <div id="nav_grid">
                @Html.PagedListPager(Model, page => Url.Action("DSSanPham", "KhuyenMai", new { key = @ViewBag.key, maloai = @ViewBag.maloai, makm = ViewBag.makm, page = page }))
            </div>
        </div>
        <div class="col-xs-12 col-sm-6">
            <div class="result-counter">
                Có tât cả <span>@Model.TotalItemCount</span> dòng
            </div>
        </div>
    </div><!-- /.row -->
</div><!-- /.pagination-holder -->

<div id="show-dialog-detail" class="form-horizontal" style="display:none">

    <div class="modal fade in" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="false" style="display: block;">

        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" onclick="closeDialog();">×</button>
                    <h3> Thông tin khuyến mãi sản phẩm </h3>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label class="control-label col-md-3" for="NgayKetThuc">Giảm giá</label>
                        <div class="col-md-2">
                            <input id="giamgiainfo" type="number" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3">Nội dung khuyến mại</label>
                        <div class="col-md-9">
                            <textarea id="motainfo" class="form-control" rows="3"></textarea>
                            <script>
                                CKEDITOR.replace('motainfo');
                            </script>

                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-5">
                            <a id="info-ok" class="btn btn-success" href='javascript:'>
                                OK
                            </a>
                        </div>
                    </div>
                </div>
                @*<div class="modal-footer">
                        <a href="#" class="btn btn-default" data-dismiss="modal">Close</a>
                        <a href="#" class="btn btn-primary" data-dismiss="modal">Save changes</a>
                    </div>*@
            </div>
        </div>
    </div>
</div>

WebSportOnline/WebSportOnline/Views/KhuyenMai/DSSanPhamKhuyenMai.cshtml
@using WebSportOnline.Models;
@using PagedList;
@using PagedList.Mvc;
@model PagedList.IPagedList<SanPham>


<table class="table table-striped table-bordered bootstrap-datatable datatable responsive">
    <thead>
        <tr>
            <th>
                <input type="checkbox" onclick="toggle(this)" />
            </th>
            <th>@Html.DisplayNameFor(model => model.First().TenSP)</th>
            <th>@Html.DisplayNameFor(model => model.First().LoaiSP1.TenLoai)</th>
            <th>@Html.DisplayNameFor(model => model.First().SoLuong)</th>
            <th>@Html.DisplayNameFor(model => model.First().GiaTien)</th>
            <th>Hành động</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <input type="checkbox" name="lstdel" value="@item.MaSP" />
                </td>
                <td class="center">@item.TenSP</td>
                <td class="center">@item.LoaiSP1.TenLoai</td>
                <td class="center">@item.SoLuong</td>
                <td class="center">@string.Format("{0:0,0}", item.GiaTien) VNĐ</td>
                <td class="center">
                    <a class="btn btn-info" href='javascript:'>
                        <i class="glyphicon glyphicon-wrench icon-white"></i>
                        Sửa thông tin
                    </a>
                    <a class="btn btn-danger" href='javascript:XoaSPKhuyenMai("@Url.Action("DeleteSPKhuyenMai", "KhuyenMai")","@ViewBag.makm","@item.MaSP")'>
                        <i class="glyphicon glyphicon-trash icon-white"></i>
                        Xóa khỏi danh sách khuyến mại
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="pagination-holder">
    <div class="row">
        <div class="col-xs-12 col-sm-6 text-left">
            <div id="nav_grid1">
                @Html.PagedListPager(Model, page => Url.Action("DSSanPhamKhuyenMai", "KhuyenMai", new { key = @ViewBag.key, maloai = @ViewBag.maloai, makm = ViewBag.makm, page = page }))
            </div>
        </div>
        <div class="col-xs-12 col-sm-6">
            <div class="result-counter">
                Có tât cả <span>@Model.TotalItemCount</span> dòng
            </div>
        </div>
    </div><!-- /.row -->
</div><!-- /.pagination-holder -->

WebSportOnline/WebSportOnline/Views/KhuyenMai/EditKhuyenMai.cshtml
@model WebSportOnline.Models.KhuyenMai
@{
    ViewBag.Title = "Sửa thông tin hãng sản xuất";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<script src="~/ckeditor/ckeditor.js"></script>
<div class="row">
    <div class="box col-md-12">
        <div class="box-inner">
            <div class="box-header well" data-original-title="">
                <h2><i class="glyphicon glyphicon-user"></i>@ViewBag.Title</h2>
                <div class="box-icon">
                    <a href="#" class="btn btn-setting btn-round btn-default"><i class="glyphicon glyphicon-cog"></i></a>
                    <a href="#" class="btn btn-minimize btn-round btn-default">
                        <i class="glyphicon glyphicon-chevron-up"></i>
                    </a>
                    <a href="#" class="btn btn-close btn-round btn-default"><i class="glyphicon glyphicon-remove"></i></a>
                </div>
            </div>
            <div class="box-content">
                @using (Html.BeginForm("EditKhuyenMai", "KhuyenMai", FormMethod.Post, new { id = "sualoaisp", autocomplete = "off", enctype = "multipart/form-data" }))
                {

                    <div class="form-horizontal">
                        <div class="alert alert-info" style="display:none">
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary()
                            <span id="kiemtratrung"></span>
                        </div>
                        @Html.HiddenFor(model => model.MaKM)
                        <div class="form-group">
                            @Html.LabelFor(model => model.TenCT, new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.TextBoxFor(model => model.TenCT, new { @class = "form-control", oninput = "kiemgiatritrung(this.value,\"" + @Url.Action("kiemtra", "KhuyenMai") + "\",\"#loaiisok\")" })
                                @Html.ValidationMessageFor(model => model.TenCT)
                                <span id="loaiisok"></span>
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.NgayBatDau, new { @class = "control-label col-md-2" })
                            <div class="col-md-3">
                                @Html.EditorFor(model => model.NgayBatDau, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.NgayBatDau)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.NgayKetThuc, new { @class = "control-label col-md-2" })
                            <div class="col-md-3">
                                @Html.EditorFor(model => model.NgayKetThuc, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.NgayKetThuc)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.AnhCT, new { @class = "control-label col-md-2" })
                            <div class="col-md-3">
                                <img id="anhdaidien" src="@Url.Content("~/images/khuyenmai/")@Model.AnhCT" alt="your image" width="360" height="250" />
                                <input type="file" name="ad" accept=".jpg" class="form-control" onchange="readURL(this, '#anhdaidien');" />
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.NoiDung, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.NoiDung, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.NoiDung)
                                <script>
                                    CKEDITOR.replace('NoiDung');
                                </script>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <a class="btn btn-danger" href="@Url.Action("SuaCTKhuyenMai", "KhuyenMai", new { MaKM = Model.MaKM })">
                                    <i class="glyphicon glyphicon-wrench icon-white"></i>
                                    Sửa danh sách sản phẩm
                                </a>
                                <a class="btn btn-info" href='javascript: submitform("sualoaisp")'>
                                    <i class="glyphicon glyphicon-wrench icon-white"></i>
                                    Cập nhật
                                </a>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    <!--/span-->
</div><!--/row-->

WebSportOnline/WebSportOnline/Views/KhuyenMai/Index.cshtml
@model WebSportOnline.Models.KhuyenMai
@{
    ViewBag.Title = "Chương trình khuyến mãi";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<script src="~/ckeditor/ckeditor.js"></script>
<div class="row">
    <div class="box col-md-12">
        <div class="box-inner">
            <div class="box-header well" data-original-title="">
                <h2><i class="glyphicon glyphicon-user"></i>@ViewBag.Title</h2>
                <div class="box-icon">
                    <a href="#" class="btn btn-setting btn-round btn-default"><i class="glyphicon glyphicon-cog"></i></a>
                    <a href="#" class="btn btn-minimize btn-round btn-default">
                        <i class="glyphicon glyphicon-chevron-up"></i>
                    </a>
                    <a href="#" class="btn btn-close btn-round btn-default"><i class="glyphicon glyphicon-remove"></i></a>
                </div>
            </div>
            <div class="box-content">
                <div class="alert alert-info" id="alert-info" style="display:none"></div>
                <div class="form-inline" style="text-align: right; padding: 10px">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="red">Start</i></span>
                        <input id="startday" type="date" class="form-control" onchange="timkiemKhuyenMai()">
                    </div>

                    <div class="input-group">
                        <span class="input-group-addon"><i class="red">End</i></span>
                        <input id="endday" type="date" class="form-control" onchange="timkiemKhuyenMai()">
                    </div>

                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-search red"></i></span>
                        <input id="inputIcon" type="text" class="form-control" placeholder="Nhập tên chương trình" oninput="timkiemKhuyenMai()">
                    </div>
                    <div class="input-group">
                        <a class="btn btn-danger" href='javascript:multibledel("@Url.Action("MultibleDel", "KhuyenMai")")'>
                            <i class="glyphicon glyphicon-trash icon-white"></i>
                            Xóa chương trình đã chọn
                        </a>
                    </div>

                </div>
                <div class="Ajax-Table">
                    @Html.Action("TimKhuyenMai", "KhuyenMai")
                </div>

            </div>
        </div>
    </div>
    <!--/span-->
</div><!--/row-->

<div class="row">
    <div class="box col-md-12">
        <div class="box-inner">
            <div class="box-header well" data-original-title="">
                <h2><i class="glyphicon glyphicon-user"></i>Thêm @ViewBag.Title</h2>
                <div class="box-icon">
                    <a href="#" class="btn btn-setting btn-round btn-default"><i class="glyphicon glyphicon-cog"></i></a>
                    <a href="#" class="btn btn-minimize btn-round btn-default">
                        <i class="glyphicon glyphicon-chevron-up"></i>
                    </a>
                    <a href="#" class="btn btn-close btn-round btn-default"><i class="glyphicon glyphicon-remove"></i></a>
                </div>
            </div>
            <div class="box-content">

                @using (Html.BeginForm("ThemKhuyenMai", "KhuyenMai", FormMethod.Post, new { autocomplete = "off", enctype = "multipart/form-data" }))
                {

                    <div class="form-horizontal">
                        <div class="alert alert-info" style="display:none">
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary()
                            <span id="kiemtratrung"></span>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.TenCT, new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.TextBoxFor(model => model.TenCT, new { @class = "form-control", oninput = "kiemgiatritrung(this.value,\"" + @Url.Action("kiemtra", "KhuyenMai") + "\",\"#loaiisok\")" })
                                @Html.ValidationMessageFor(model => model.TenCT)
                                <span id="loaiisok"></span>
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.NgayBatDau, new { @class = "control-label col-md-2" })
                            <div class="col-md-3">
                                @Html.EditorFor(model => model.NgayBatDau, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.NgayBatDau)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.NgayKetThuc, new { @class = "control-label col-md-2" })
                            <div class="col-md-3">
                                @Html.EditorFor(model => model.NgayKetThuc, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.NgayKetThuc)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.AnhCT, new { @class = "control-label col-md-2" })
                            <div class="col-md-3">
                                <img id="anhdaidien" src="@Url.Content("~/template/")assets/images/blank.gif" alt="your image" width="360" height="250" />
                                <input type="file" name="ad" accept=".jpg" class="form-control" onchange="readURL(this, '#anhdaidien');" />
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.NoiDung, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.NoiDung, new { @class = "form-control"  })
                                @Html.ValidationMessageFor(model => model.NoiDung)
                                <script>
                                    CKEDITOR.replace('NoiDung');
                                </script>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Thêm mới" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }

            </div>

        </div>
    </div>
    <!--/span-->
</div><!--/row-->

WebSportOnline/WebSportOnline/Views/KhuyenMai/KhuyenMaiDetail.cshtml
@model IQueryable<WebSportOnline.Models.SanPhamKhuyenMai> 

<div class="modal fade in" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="false" style="display: block;">

    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" onclick="closeDialog();">×</button>
                <h3> @Model.First().KhuyenMai.TenCT </h3>
            </div>
            <div class="modal-body">
                <table class="table-hover table-bordered">
                    <tr>
                        <th>@Html.DisplayNameFor(model=>model.First().SanPham.TenSP)</th>
                        <th>@Html.DisplayNameFor(model => model.First().GiamGia)</th>
                        <th>@Html.DisplayNameFor(model => model.First().MoTa)</th>
                    </tr>

                @foreach(var item in Model)
                {
                    <tr>
                        <td>@item.SanPham.TenSP</td>
                        <td>@item.GiamGia</td>
                        <td>@Html.Raw(@item.MoTa)</td>
                    </tr>
                }                   
                </table>
            </div>
            @*<div class="modal-footer">
                    <a href="#" class="btn btn-default" data-dismiss="modal">Close</a>
                    <a href="#" class="btn btn-primary" data-dismiss="modal">Save changes</a>
                </div>*@
        </div>
    </div>
</div>