WebSportOnline/WebSportOnline/Controllers/HangSXController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using WebSportOnline.Models;
using System.Net;


namespace WebSportOnline.Controllers
{
    [AuthLog(Roles = "Quản trị viên,Nhân viên")]
    public class HangSXController : Controller
    {
        //
        // GET: /HangSX/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult EditHangSX(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HangSanXuatModel lm = new HangSanXuatModel();
            HangSanXuat sp = lm.FindById(id);
            if (sp == null)
            {
                return HttpNotFound();
            }
            return View(sp);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditHangSX([Bind(Include = "HangSX,TenHang,TruSoChinh,QuocGia")] HangSanXuat loai)
        {
            HangSanXuatModel spm = new HangSanXuatModel();
            if (ModelState.IsValid)
            {
                spm.EditHangSX(loai);
                return RedirectToAction("Index");
            }
            return View(loai);
        }

        public ActionResult DeleteHangSX(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HangSanXuatModel spm = new HangSanXuatModel();
            if (spm.FindById(id) == null)
            {
                return HttpNotFound();
            }
            spm.DeleteHangSX(id);
            return TimHangSX(null, null);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ThemHangSX([Bind(Include = "TenHang,TruSoChinh,QuocGia")] HangSanXuat loai)
        {
            HangSanXuatModel spm = new HangSanXuatModel();
            if (ModelState.IsValid && spm.KiemTraTen(loai.TenHang))
            {
                string maloai = spm.ThemHangSX(loai);
                return View("Index");
            }
            return View("Index", loai);
        }

        [HttpPost]
        public ActionResult MultibleDel(List<string> lstdel)
        {
            if (lstdel == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            foreach (var item in lstdel)
            {
                HangSanXuatModel spm = new HangSanXuatModel();
                if (spm.FindById(item) == null)
                {
                    return HttpNotFound();
                }
                spm.DeleteHangSX(item);
            }
            return TimHangSX(null, null);
        }

        public ActionResult TimHangSX(string key, int? page)
        {
            HangSanXuatModel spm = new HangSanXuatModel();
            ViewBag.key = key;
            return PhanTrangHangSX(spm.SearchByName(key), page, null);
        }

        public ActionResult PhanTrangHangSX(IQueryable<HangSanXuat> lst, int? page, int? pagesize)
        {
            int pageSize = (pagesize ?? 10);
            int pageNumber = (page ?? 1);
            return PartialView("HangSXPartial", lst.OrderBy(m => m.TenHang).ToPagedList(pageNumber, pageSize));
        }

        public ActionResult kiemtra(string key)
        {
            HangSanXuatModel spm = new HangSanXuatModel();
            if (spm.KiemTraTen(key))
                return Json(true, JsonRequestBehavior.AllowGet);
            return Json(false, JsonRequestBehavior.AllowGet);
        }
	}
}

WebSportOnline/WebSportOnline/Views/HangSX/EditHangSX.cshtml
@model WebSportOnline.Models.HangSanXuat
@{
    ViewBag.Title = "Sửa thông tin hãng sản xuất";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="row">
    <div class="box col-md-12">
        <div class="box-inner">
            <div class="box-header well" data-original-title="">
                <h2><i class="glyphicon glyphicon-user"></i>@ViewBag.Title</h2>
                <div class="box-icon">
                    <a href="#" class="btn btn-setting btn-round btn-default"><i class="glyphicon glyphicon-cog"></i></a>
                    <a href="#" class="btn btn-minimize btn-round btn-default">
                        <i class="glyphicon glyphicon-chevron-up"></i>
                    </a>
                    <a href="#" class="btn btn-close btn-round btn-default"><i class="glyphicon glyphicon-remove"></i></a>
                </div>
            </div>
            <div class="box-content">
                @using (Html.BeginForm("EditHangSX", "HangSX", FormMethod.Post, new { id = "sualoaisp", autocomplete = "off" }))
                {

                    <div class="form-horizontal">
                        <div class="alert alert-info" style="display:none">
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary()
                            <span id="kiemtratrung"></span>
                        </div>
                        @Html.HiddenFor(model => model.HangSX)
                        <div class="form-group">
                            @Html.LabelFor(model => model.TenHang, new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.TextBoxFor(model => model.TenHang, new { @class = "form-control", oninput = "kiemgiatritrung(this.value,\"" + @Url.Action("kiemtra", "HangSX") + "\",\"#loaiisok\")" })
                                @Html.ValidationMessageFor(model => model.TenHang)
                                <span id="loaiisok"></span>
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.TruSoChinh, new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.TextBoxFor(model => model.TruSoChinh, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.TruSoChinh)
                                <span id="loaiisok"></span>
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.QuocGia, new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.TextBoxFor(model => model.QuocGia, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.QuocGia)
                                <span id="loaiisok"></span>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <a class="btn btn-info" href='javascript: submitform("sualoaisp")'>
                                    <i class="glyphicon glyphicon-wrench icon-white"></i>
                                    Cập nhật
                                </a>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    <!--/span-->
</div><!--/row-->

WebSportOnline/WebSportOnline/Views/HangSX/HangSXPartial.cshtml
@using WebSportOnline.Models;
@using PagedList;
@using PagedList.Mvc;
@model PagedList.IPagedList<HangSanXuat>


<table class="table table-striped table-bordered bootstrap-datatable datatable responsive">
    <thead>
        <tr>
            <th>
                <input type="checkbox" onclick="toggle(this)" />
            </th>
            <th>@Html.DisplayNameFor(model => model.First().TenHang)</th>
            <th>@Html.DisplayNameFor(model => model.First().TruSoChinh)</th>
            <th>@Html.DisplayNameFor(model => model.First().QuocGia)</th>
            <th>Hành động</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <input type="checkbox" name="lstdel" value="@item.HangSX" />
                </td>
                <td class="center">@item.TenHang</td>
                <td class="center">@item.TruSoChinh</td>
                <td class="center">@item.QuocGia</td>
                <td class="center">
                    <a class="btn btn-info" href="@Url.Action("EditHangSX", "HangSX", new { id = item.HangSX })">
                        <i class="glyphicon glyphicon-edit icon-white"></i>
                        Sửa
                    </a>
                    <a class="btn btn-danger" href='javascript:XoaItem("@Url.Action("DeleteHangSX", "HangSX")","@item.HangSX")'>
                        <i class="glyphicon glyphicon-trash icon-white"></i>
                        Xóa
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="pagination-holder">
    <div class="row">
        <div class="col-xs-12 col-sm-6 text-left">
            <div id="nav_grid">
                @Html.PagedListPager(Model, page => Url.Action("TimHangSX", "HangSX", new { key = @ViewBag.key, page = page }))
            </div>
        </div>
        <div class="col-xs-12 col-sm-6">
            <div class="result-counter">
                Có tât cả <span>@Model.TotalItemCount</span> dòng
            </div>
        </div>
    </div><!-- /.row -->
</div><!-- /.pagination-holder -->

WebSportOnline/WebSportOnline/Views/HangSX/Index.cshtml
@model WebSportOnline.Models.HangSanXuat
@{
    ViewBag.Title = "Hãng sản xuất";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="row">
    <div class="box col-md-12">
        <div class="box-inner">
            <div class="box-header well" data-original-title="">
                <h2><i class="glyphicon glyphicon-user"></i>@ViewBag.Title</h2>
                <div class="box-icon">
                    <a href="#" class="btn btn-setting btn-round btn-default"><i class="glyphicon glyphicon-cog"></i></a>
                    <a href="#" class="btn btn-minimize btn-round btn-default">
                        <i class="glyphicon glyphicon-chevron-up"></i>
                    </a>
                    <a href="#" class="btn btn-close btn-round btn-default"><i class="glyphicon glyphicon-remove"></i></a>
                </div>
            </div>
            <div class="box-content">
                <div class="alert alert-info" id="alert-info" style="display:none"></div>
                <div class="form-inline" style="text-align: right; padding: 10px">

                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-search red"></i></span>
                        <input id="inputIcon" type="text" class="form-control" placeholder="Nhập tên hãng" oninput="timkiemHangSX()">
                    </div>
                    <div class="input-group">
                        <a class="btn btn-danger" href='javascript:multibledel("@Url.Action("MultibleDel", "HangSX")")'>
                            <i class="glyphicon glyphicon-trash icon-white"></i>
                            Xóa các hãng đã chọn
                        </a>
                    </div>

                </div>
                <div class="Ajax-Table">
                    @Html.Action("TimHangSX", "HangSX")
                </div>

            </div>
        </div>
    </div>
    <!--/span-->
</div><!--/row-->

<div class="row">
    <div class="box col-md-12">
        <div class="box-inner">
            <div class="box-header well" data-original-title="">
                <h2><i class="glyphicon glyphicon-user"></i>Thêm @ViewBag.Title</h2>
                <div class="box-icon">
                    <a href="#" class="btn btn-setting btn-round btn-default"><i class="glyphicon glyphicon-cog"></i></a>
                    <a href="#" class="btn btn-minimize btn-round btn-default">
                        <i class="glyphicon glyphicon-chevron-up"></i>
                    </a>
                    <a href="#" class="btn btn-close btn-round btn-default"><i class="glyphicon glyphicon-remove"></i></a>
                </div>
            </div>
            <div class="box-content">

                @using (Html.BeginForm("ThemHangSX", "HangSX", FormMethod.Post, new { autocomplete = "off" }))
                {

                    <div class="form-horizontal">
                        <div class="alert alert-info" style="display:none">
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary()
                            <span id="kiemtratrung"></span>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.TenHang, new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.TextBoxFor(model => model.TenHang, new { @class = "form-control", oninput = "kiemgiatritrung(this.value,\"" + @Url.Action("kiemtra", "HangSX") + "\",\"#loaiisok\")" })                         
                                @Html.ValidationMessageFor(model => model.TenHang)
                                <span id="loaiisok"></span>
                            </div>
                        </div>  
                        
                        <div class="form-group">
                            @Html.LabelFor(model => model.TruSoChinh, new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.TextBoxFor(model => model.TruSoChinh, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.TruSoChinh)                         
                            </div>
                        </div> 
                        
                        <div class="form-group">
                            @Html.LabelFor(model => model.QuocGia, new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.TextBoxFor(model => model.QuocGia, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.QuocGia)
                            </div>
                        </div>                  

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Thêm mới" class="btn btn-default"/>
                            </div>
                        </div>
                    </div>
                }

            </div>

        </div>
    </div>
    <!--/span-->
</div><!--/row-->